version: v1.3.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4435
    port: 4435
    cors:
      enabled: true
  admin:
    base_url: http://127.0.0.1:4436
    port: 4436

selfservice:
  default_browser_return_url: http://127.0.0.1:8081/
  allowed_return_urls:
    - http://127.0.0.1:8081

  methods:
    password:
      enabled: true
      config:
        min_password_length: 8
        identifier_similarity_check_enabled: false
        haveibeenpwned_enabled: false

log:
  format: text
  leak_sensitive_values: true
  level: info

secrets:
  cookie:
    - CHANGE_ME_TO_REAL_SECRET
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

