AWSTemplateFormatVersion: "2010-09-09"
Description: CF template to create dynamodb tables.
Resources:

  # ====================
  # | Dynamodb tables  |
  # ====================

  ProjectsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Projects
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lsi1_sk
          AttributeType: S
        - AttributeName: lsi2_sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI1_CreationDateTime
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: GSI2_ProjectName
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      TableClass: STANDARD

  QuotesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Quotes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lsi1_sk
          AttributeType: S
        - AttributeName: gsi1_sk
          AttributeType: S
        - AttributeName: gsi2_pk
          AttributeType: S
        - AttributeName: gsi2_sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI1_ProjectAndCreationDateTime
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: GSI1_QuoteStatus
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: gsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2_QuoteIsPendingReview
          KeySchema:
            - AttributeName: gsi2_pk
              KeyType: HASH
            - AttributeName: gsi2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      TableClass: STANDARD

  PartsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Parts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lsi1_sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI1_QuoteAndCreationDateTime
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      TableClass: STANDARD

  OrdersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Orders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lsi1_sk
          AttributeType: S
        - AttributeName: lsi2_sk
          AttributeType: S
        - AttributeName: gsi1_sk
          AttributeType: S
        - AttributeName: gsi2_pk
          AttributeType: S
        - AttributeName: gsi2_sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI1_CreationDateTime
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: LSI2_ProjectAndQuoteAndPart
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: GSI1_OrderStatus
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: gsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2_OrderIsOpen
          KeySchema:
            - AttributeName: gsi2_pk
              KeyType: HASH
            - AttributeName: gsi2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      TableClass: STANDARD
