AWSTemplateFormatVersion: "2010-09-09"
Description: CF template to create dynamodb tables to handle orders
Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: order_status
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: OrdersByStatus
          KeySchema:
            - AttributeName: order_status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      TableClass: STANDARD
      TableName: Orders

Outputs:
  OrdersTableArn:
    Description: ARN of orders dynamodb table.
    Value: !GetAtt OrdersTable.Arn
    Export:
      Name: OrdersTableArn
