[package]
name = "api-boundary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0.193"
serde = { version = "1.0.193", features = ["derive"] }
