AWSTemplateFormatVersion: "2010-09-09"
Description: CF template to create TLS/SSL certificates.
Resources:
  ClientPortalCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: www.torvek.com
      ValidationMethod: DNS

  AdminPortalCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: admin.torvek.com
      ValidationMethod: DNS

  SupplierPortalCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: suppliers.torvek.com
      ValidationMethod: DNS

  SuppliersAuthCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: auth.suppliers.torvek.com
      ValidationMethod: DNS

  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: api.torvek.com
      ValidationMethod: DNS

Outputs:
  ClientPortalCertificateArn:
    Description: ARN for client portal certificate.
    Value: !Ref ClientPortalCertificate
    Export:
      Name: ClientPortalCertificateArn
  AdminPortalCertificateArn:
    Description: ARN for admin portal certificate.
    Value: !Ref AdminPortalCertificate
    Export:
      Name: AdminPortalCertificateArn
  SupplierPortalCertificateArn:
    Description: ARN for supplier portal certificate.
    Value: !Ref SupplierPortalCertificate
    Export:
      Name: SupplierPortalCertificateArn
