AWSTemplateFormatVersion: "2010-09-09"
Description: CF template to create S3 buckets.
Resources:
  LandingPageWebAppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-landing-page-web
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  CustomerWebAppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-customer-web
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  AdminWebAppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-admin-web
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  SupplierWebAppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-supplier-web
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  CustomerFilesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-customer-files
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            Id: CorsRule
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: parts/originals/
            Function: !ImportValue FileConverterLambdaArn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ConfigFilesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-config-files
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            Id: CorsRule
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

Outputs:
  LandingPageWebAppBucketName:
    Description: Name of the landing page web app bucket.
    Value: !Ref LandingPageWebAppBucket
    Export:
      Name: LandingPageWebAppBucketName
  LandingPageWebAppBucketArn:
    Description: ARN of the landing page web app bucket.
    Value: !GetAtt LandingPageWebAppBucket.Arn
    Export:
      Name: LandingPageWebAppBucketArn
  LandingPageWebAppBucketDomainName:
    Description: Domain name of the landing page web bucket.
    Value: !GetAtt LandingPageWebAppBucket.DomainName
    Export:
      Name: LandingPageWebAppBucketDomainName

  CustomerWebAppBucketName:
    Description: Name of the customer web app bucket.
    Value: !Ref CustomerWebAppBucket
    Export:
      Name: CustomerWebAppBucketName
  CustomerWebAppBucketArn:
    Description: ARN of the customer web app bucket.
    Value: !GetAtt CustomerWebAppBucket.Arn
    Export:
      Name: CustomerWebAppBucketArn
  CustomerWebAppBucketDomainName:
    Description: Domain name of the customer web app bucket.
    Value: !GetAtt CustomerWebAppBucket.DomainName
    Export:
      Name: CustomerWebAppBucketDomainName

  AdminWebAppBucketName:
    Description: Name of the admin web app bucket.
    Value: !Ref AdminWebAppBucket
    Export:
      Name: AdminWebAppBucketName
  AdminWebAppBucketArn:
    Description: ARN of the admin web app bucket.
    Value: !GetAtt AdminWebAppBucket.Arn
    Export:
      Name: AdminWebAppBucketArn
  AdminWebAppBucketDomainName:
    Description: Domain name of the admin web app bucket.
    Value: !GetAtt AdminWebAppBucket.DomainName
    Export:
      Name: AdminWebAppBucketDomainName

  SupplierWebAppBucketName:
    Description: Name of the supplier web app bucket.
    Value: !Ref SupplierWebAppBucket
    Export:
      Name: SupplierWebAppBucketName
  SupplierWebAppBucketArn:
    Description: ARN of the supplier web app bucket.
    Value: !GetAtt SupplierWebAppBucket.Arn
    Export:
      Name: SupplierWebAppBucketArn
  SupplierWebAppBucketDomainName:
    Description: Domain name of the supplier web app bucket.
    Value: !GetAtt SupplierWebAppBucket.DomainName
    Export:
      Name: SupplierWebAppBucketDomainName

  CustomerFilesBucketName:
    Description: Name of bucket to store files from customers.
    Value: !Ref CustomerFilesBucket
    Export:
      Name: CustomerFilesBucketName
  CustomerFilesBucketArn:
    Description: ARN of bucket to store files from customers.
    Value: !GetAtt CustomerFilesBucket.Arn
    Export:
      Name: CustomerFilesBucketArn

  ConfigFilesBucketName:
    Description: Name of bucket to store app config files.
    Value: !Ref ConfigFilesBucket
    Export:
      Name: ConfigFilesBucketName
  ConfigFilesBucketArn:
    Description: ARN of bucket to store app config files.
    Value: !GetAtt ConfigFilesBucket.Arn
    Export:
      Name: ConfigFilesBucketArn
