AWSTemplateFormatVersion: "2010-09-09"
Description: CF template to create S3 permissions.
Resources:
  ClientPortalBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue ClientPortalBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Sid: AllowCloudFrontServicePrincipal
          Action:
            - 's3:GetObject'
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Resource: !Join
            - ""
            - - !ImportValue ClientPortalBucketArn
              - /*
          Condition:
            StringEquals:
              AWS:SourceArn: !Join
                - ""
                - - arn:aws:cloudfront::120386585975:distribution/
                  - !ImportValue ClientPortalCloudFrontDistributionId

  AdminPortalBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue AdminPortalBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Sid: AllowCloudFrontServicePrincipal
          Action:
            - 's3:GetObject'
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Resource: !Join
            - ""
            - - !ImportValue AdminPortalBucketArn
              - /*
          Condition:
            StringEquals:
              AWS:SourceArn: !Join
                - ""
                - - arn:aws:cloudfront::120386585975:distribution/
                  - !ImportValue AdminPortalCloudFrontDistributionId

  SupplierPortalBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue SupplierPortalBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Sid: AllowCloudFrontServicePrincipal
          Action:
            - 's3:GetObject'
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Resource: !Join
            - ""
            - - !ImportValue SupplierPortalBucketArn
              - /*
          Condition:
            StringEquals:
              AWS:SourceArn: !Join
                - ""
                - - arn:aws:cloudfront::120386585975:distribution/
                  - !ImportValue SupplierPortalCloudFrontDistributionId
