AWSTemplateFormatVersion: "2010-09-09"
Description: CF template to create S3 buckets.
Resources:

  # ===============
  # | Permissions |
  # ===============

  S3PermissionForFileConverterLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:file_converter'
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::torvek-customer-files-staging

  # ==============
  # | S3 Buckets |
  # ==============

  WebAppsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-web-apps-staging
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  CustomerFilesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-customer-files-staging
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            Id: CorsRule
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: parts/originals/
            Function: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:file_converter'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ConfigFilesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: torvek-config-files-staging
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            Id: CorsRule
      LifecycleConfiguration:
        Rules:
          - Id: OldVersionsExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
