name: torvek-test
services:
  localstack:
    container_name: localstack-test
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4576:4566"            # LocalStack Gateway (shifted from 4566)
      - "127.0.0.1:4520-4569:4510-4559"  # external services port range (shifted)
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - HOST_TMP_FOLDER=${PWD}/localstack_tmp_test
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
      - "${LOCALSTACK_VOLUME_DIR:-./volumes/localstack-test}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  file_converter:
    container_name: file_converter-test
    build: ./scripts/local_file_converter
    environment:
      - AWS_ENDPOINT_URL=http://host.docker.internal:4576  # Updated to test LocalStack port
      - QUEUE_URL=http://sqs.us-east-1.localhost.localstack.cloud:4576/000000000000/file-converter-queue  # Updated port
    depends_on:
      - localstack

  kratos-customers:
    container_name: kratos-customers-test
    image: oryd/kratos:v1.3.0
    ports:
      - '4443:4443' # public (shifted from 4433)
      - '4444:4444' # admin (shifted from 4434)
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    entrypoint: [ "sh", "/etc/scripts/kratos/entrypoint-test.sh" ]
    volumes:
      - type: volume
        source: kratos-customers-sqlite-test
        target: /var/lib/sqlite
      - type: bind
        source: ./config/kratos/customers
        target: /etc/config/kratos
      - type: bind
        source: ./scripts/kratos
        target: /etc/scripts/kratos

  kratos-admins:
    container_name: kratos-admins-test
    image: oryd/kratos:v1.3.0
    ports:
      - '4435:4435' # public (shifted from 4435)
      - '4436:4436' # admin (shifted from 4436)
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    entrypoint: [ "sh", "/etc/scripts/kratos/entrypoint.sh" ]
    volumes:
      - type: volume
        source: kratos-admins-sqlite-test
        target: /var/lib/sqlite
      - type: bind
        source: ./config/kratos/admins
        target: /etc/config/kratos
      - type: bind
        source: ./scripts/kratos
        target: /etc/scripts/kratos

volumes:
  kratos-customers-sqlite-test:
  kratos-admins-sqlite-test:
