name: torvek
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
      # Logs, cache and generated data by AWS services live here.
      - "${LOCALSTACK_VOLUME_DIR:-./volumes/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  file_converter:
    container_name: file_converter
    build: ./scripts/local_file_converter
    environment:
      - AWS_ENDPOINT_URL=http://host.docker.internal:4566
      - QUEUE_URL=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/file-converter-queue
    depends_on:
      - localstack

  ory-kratos:
    container_name: ory-kratos
    image: oryd/kratos:v1.3.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    entrypoint: [ "sh", "/etc/scripts/kratos/entrypoint.sh" ]
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
      - type: bind
        source: ./scripts/kratos
        target: /etc/scripts/kratos

volumes:
  kratos-sqlite:
